name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      #- name: Stop PM2 process
      #  run: pm2 stop gizmo-chat-server
      
      #- name: GIT checkout
      #  uses: actions/checkout@v2
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.HOST }}

      - name: GIT
        run: >
          ssh staging "
            cd /home/ubuntu/gizmo-chat-server &&
            git pull origin master
          "

      - name: Build NPM dependencies
        run: >
          ssh staging "
            cd /home/ubuntu/gizmo-chat-server &&
            rm -rf ./node_modules &&
            rm -rf ./build &&
            npm ci --only=production &&
            npm run build
          "

      - name: Finish
        run: >
          ssh staging "
            echo "NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA " 
          "

      #- name: Build NPM dependencies
      #  run: |
      #    cd /home/ubuntu/gizmo-chat-server
      #    rm -rf ./node_modules
      #    rm -rf ./build
      #    npm ci --only=production
      #    npm run build
        
      #- name: Start PM2 process
      #  run: |
      #    pm2 start npm --name gizmo-chat-server -- start
      #   echo "NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA " 