name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          pm2 stop gizmo-chat-server && pm2 delete gizmo-chat-server
          cd /home/ubuntu/gizmo-chat-server
          git pull origin master
          rm -rf ./node_modules
          rm -rf ./build
          npm ci
          npm run build
          pm2 start gizmo-chat-server

    - name: Finish
      run: |
        echo "NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA "