name: Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [ 14.x ]
    
    steps:

      - name: Stop PM2 process
        run: pm2 stop gizmo-chat-server && pm2 delete gizmo-chat-server
      
      - name: GIT checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build Node.js dependencies
        run: npm ci && npm run build --if-present

      - name: Create .env file and inject environmental variables
        run: |
          touch .env
          echo "
            NODE_ENV=production
            PORT=${{ secrets.PORT }}
          " >> .env

      - name: Create cert.pem and key.pem files
        run: |
          touch cert.pem
          echo "${{ secrets.CERT_PEM }}" >> cert.pem
          touch key.pem
          echo "${{ secrets.KEY_PEM }}" >> key.pem

      - name: Start PM2 process
        run: pm2 start npm --name gizmo-chat-server -- start && echo 'NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA NA '