name: Deploy Dockerfile to Azure

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.DOCKERIO_USERNAME }}
        password: ${{ secrets.DOCKERIO_PASSWORD }}
    - run: |
        docker build . -t gizmo.azurecr.io/gizmo-chat-server:${{ github.sha }}
        docker push gizmo.azurecr.io/gizmo-chat-server:${{ github.sha }}         

    - uses: azure/webapps-deploy@v2
      with:
        app-name: gizmo-chat-server
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: gizmo.azurecr.io/gizmo-chat-server:${{ github.sha }}