name: Azure Deployment

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Build Node.js dependencies
      run: npm ci && npm run build --if-present

    - name: Create .env file and inject environmental variables
      run: |
        touch .env
        echo "
          NODE_ENV=production
        " >> .env

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: gizmo-chat-server
        slot-name: production
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f910e896efe4416092ee9dfe8964c5fd }}
        package: .